### ISSUE TITLE
Problems after installing addon and start development server

### ISSUE THREAD

**Issue by marceloboth** [Deveo/ember-drag-sort#9] opened 2017-09-20 01:02 UTC
I'm trying to use this addon, but when I start my development server this error become on the screen:

```
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (appTestTrees)] failed with:
SyntaxError: <my-project>/tests/pages/components/_component.js: Unexpected token (37:4)
  
  return {
...(scope ? { scope, itemScope : scope } : {}), // inject the scope only if it was provided
     |     ^
  38 | 
  39 |     $        : jquery(($el) => $el),
  40 |     attr     : jquery(($el) => (attrName) => $el.attr(attrName)),
    at Parser.pp$5.raise (/<my-project>/node_modules/babylon/lib/index.js:4454:13)
```

My Ember version is 2.15.1 and the ember-drag-sort is 1.0.0. I saw this line in your test code: [_component.js](https://github.com/Deveo/ember-drag-sort/blob/gen-0/test-support/pages/components/_component.js#L37), and can be something related to the recent version of Ember?

**Comment by lolmaus** [comment] 2017-09-20 06:52
Looks like you're running Node 4. Try Node 6.

**Comment by marceloboth** [comment] 2017-09-20 11:18
@lolmaus my environment is:
broccoli-builder@0.18.8, 
node@v6.9.0

**Comment by lolmaus** [comment] 2017-09-20 12:26
Hmm, this seems to be a duplicate of #1 which stayed unresolved.

Can you please try this:

```
npm i -D babel-plugin-transform-object-rest-spread
```

```js
// ember-cli-build.js

var app = new EmberApp({
  babel: {
    plugins: [
      'transform-object-rest-spread'
    ]
  }
});
```

**Comment by marceloboth** [comment] 2017-09-20 12:34
@lolmaus Yes it works. Sorry for didn't see the other issue before. Thanks for the help.

**Comment by lolmaus** [comment] 2017-09-20 12:39
I'll keep this open as a reminder to update the readme.

**Closed** 2017-09-20 14:36 UTC

**Comment by DelphiClaer** [comment] 2017-12-04 17:06
encountered this problem just now, the fix solved it for me
